name: CI/CD Workflow

# Definir que o trigger será acionado ao push na branch 'main'
on:
  push:
    branches:
      - main

jobs:
  # Job de build da imagem Docker
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Login no Docker Hub ou Google Artifact Registry
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Construção da imagem Docker
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sauter_university:latest .

      # Push da imagem para o Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sauter_university:latest

  # Job de deploy no GKE
  deploy:
    name: Deploy to GKE
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Autenticação com Google Cloud para acessar GKE
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Configuração do kubectl para o cluster GKE
      - name: Set up GKE
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: your-cluster-name
          location: your-cluster-region
          project_id: your-project-id

      # Aplicação do manifesto Kubernetes para deploy da nova imagem
      - name: Deploy to GKE
        run: |
          kubectl set image deployment/sauter-university sauter-university=${{ secrets.DOCKER_USERNAME }}/sauter_university:latest
